name: graphics-test-tools
version: "22.04"
base: core22
summary: Tools helpful in debugging graphics stacks
description: |
  - drm-info:
    List the capabilities and current settings of this device's DRM
    (Direct Rendering Manager) hardware.
  - glmark2-es2-wayland:
    OpenGL ES 2.0 Wayland benchmark.
  - eglinfo:
    Dump information about the available EGL setup.

grade: stable
confinement: strict

layout:
  /usr/share/libdrm:  # Needed by mesa-core22 on ARM GPUs
    bind: $SNAP/graphics/libdrm
  /usr/share/drirc.d:
    bind: $SNAP/graphics/drirc.d

plugs:
  graphics-core22:
    interface: content
    target: $SNAP/graphics
    default-provider: mesa-core22/edge

apps:
  drm-info:
    plugs:
      - opengl
    command: usr/bin/drm_info

  eglinfo:
    plugs:
      - opengl
      - wayland
    command-chain:
      - bin/graphics-core22-wrapper
      - bin/wayland-launch
    command: usr/bin/eglinfo

  eglinfo-x11:
    command: usr/bin/eglinfo
    plugs:
      - opengl
      - x11
    command-chain:
      - bin/graphics-core22-wrapper

  glmark2-es2:
    plugs:
      - opengl
      - x11
    command-chain:
      - bin/graphics-core22-wrapper
      - glmark2-wrapper
    command: usr/bin/glmark2-es2

  glmark2-es2-wayland:
    plugs:
      - opengl
      - wayland
    command-chain:
      - bin/graphics-core22-wrapper
      - bin/wayland-launch
      - glmark2-wrapper
    command: usr/bin/glmark2-es2-wayland

  glxinfo:
    plugs:
      - opengl
      - x11
    command-chain:
      - bin/graphics-core22-wrapper
    command: usr/bin/glxinfo

  vainfo:
    plugs:
      - opengl
    command-chain:
      - bin/graphics-core22-wrapper
    command: usr/bin/vainfo

  vdpauinfo:
    plugs:
      - opengl
      - x11
    command-chain:
      - bin/graphics-core22-wrapper
    command: usr/bin/vdpauinfo

  vulkaninfo:
    plugs:
      - opengl
      - x11
    command-chain:
      - bin/graphics-core22-wrapper
    command: usr/bin/vulkaninfo

  vkcube:
    plugs:
      - opengl
      - x11
    command-chain:
      - bin/graphics-core22-wrapper
    command: usr/bin/vkcube

parts:
  glue:
    plugin: dump
    source: glue

  mir-kiosk-snap-launch:
      plugin: dump
      source: https://github.com/MirServer/mir-kiosk-snap-launch.git
      override-build:  ${CRAFT_PART_BUILD}/build-with-plugs.sh opengl wayland
      stage-packages:
        - inotify-tools
      stage:
        - -README.md

  drm-info:
    plugin: nil
    stage-packages:
      - drm-info

  eglinfo:
    plugin: nil
    source: .
    stage-packages:
      - mesa-utils-extra

  glmark2:
    plugin: nil
    source: .
    stage-packages:
      - glmark2-es2
      - glmark2-es2-wayland

  vainfo:
    plugin: nil
    stage-packages:
      - vainfo

  vdpauinfo:
    plugin: nil
    stage-packages:
      - vdpauinfo

  vulkan-tools:
    plugin: nil
    stage-packages:
      - vulkan-tools

  graphics-core22:
    after:
      - drm-info
      - eglinfo
      - glmark2
      - vainfo
      - vdpauinfo
      - vulkan-tools
    source: https://github.com/MirServer/graphics-core22.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/graphics-core22-cleanup mesa-core22
      rm -rf ${CRAFT_PRIME}/usr/share/{doc,man}
    prime:
      - bin/graphics-core22-wrapper
