name: graphics-test-tools
version: "20.04"
base: core20
summary: Tools helpful in debugging graphics stacks
description: |
  - drm-info (MIT):
    List the capabilities and current settings of this device's DRM
    (Direct Rendering Manager) hardware.
  - glmark2-es2 (GPLv3):
    OpenGL ES 2.0 X11 benchmark.
  - glmark2-es2-wayland (GPLv3):
    OpenGL ES 2.0 Wayland benchmark.
  - eglinfo (MIT):
    Dump information about the available EGL setup.
  - glxinfo (MIT):
    Dump information about the available GLX setup.
  - kmscube (MIT):
    Example KMS/GBM/EGL application
  - vainfo (MIT):
    Dump information about the available VAAPI (hardware video acceleration) setup.
  - vdpauinfo (MIT):
    Dump information about the available VDPAU (hardware video acceleration) setup.
  - vulkaninfo (Apache-2.0):
    Dump information about the available Vulkan setup.
  - vkcube (Apache-2.0):
    Test the Vulkan setup.

  This snap uses the graphics-core20 interface to gain support graphics hardware.
  It can be used to verify custom graphics-core20 provider implementations.

  See https://mir-server.io/docs/the-graphics-core20-snap-interface) for more
  information.
website: https://github.com/MirServer/graphics-test-tools
contact: https://github.com/MirServer/graphics-test-tools/issues
license: Apache-2.0 AND GPL-3.0 AND MIT

grade: stable
confinement: strict

environment:
  # Setup EGL from the plugs
  LD_LIBRARY_PATH:    $SNAP/graphics/lib:$SNAP/usr/local/lib
  LIBGL_DRIVERS_PATH: $SNAP/graphics/dri
  __EGL_VENDOR_LIBRARY_DIRS: $SNAP/graphics/glvnd/egl_vendor.d

layout:
  /usr/share/libdrm:  # Needed by mesa-core20 on ARM GPUs
    bind: $SNAP/graphics/libdrm
  /usr/share/drirc.d:
    bind: $SNAP/graphics/drirc.d

plugs:
  graphics-core20:
    interface: content
    target: $SNAP/graphics
    default-provider: mesa-core20

apps:
  drm-info:
    plugs:
      - opengl
    command: usr/local/bin/drm_info

  eglinfo:
    plugs:
      - opengl
      - wayland
      - x11
    command-chain:
      - bin/wayland-launch
    command: usr/bin/eglinfo

  glmark2-es2:
    plugs:
      - opengl
      - x11
    command: usr/bin/glmark2-es2 --data-path $SNAP/usr/share/glmark2

  glmark2-es2-wayland:
    plugs:
      - opengl
      - wayland
    command-chain:
      - bin/wayland-launch
    command: usr/bin/glmark2-es2-wayland --data-path $SNAP/usr/share/glmark2

  glxinfo:
    plugs:
      - opengl
      - x11
    command: usr/bin/glxinfo

  kmscube:
    plugs:
      - opengl
    command: usr/bin/kmscube

  vainfo:
    plugs:
      - opengl
    command: usr/bin/vainfo

  vdpauinfo:
    plugs:
      - opengl
      - x11
    command: usr/bin/vdpauinfo

  vulkaninfo:
    plugs:
      - opengl
      - x11
    command: usr/bin/vulkaninfo

  vkcube:
    plugs:
      - opengl
      - x11
    command: usr/bin/vkcube

parts:
  scripts:
    plugin: dump
    source: scripts
    stage-packages:
      - inotify-tools

  drm-info:
    plugin: meson
    source: https://gitlab.freedesktop.org/emersion/drm_info.git
    source-tag: v2.3.0
    build-packages:
      - libdrm-dev
      - libjson-c-dev
      - libpci-dev
      - meson
      - pkg-config
    stage-packages:
      - libdrm2
      - libjson-c4
      - libpci3

  eglinfo:
    plugin: nil
    source: .
    stage-packages:
      - mesa-utils-extra

  glmark2:
    plugin: nil
    source: .
    stage-packages:
      - glmark2-es2
      - glmark2-es2-wayland

  glxinfo:
    plugin: nil
    stage-packages:
      - mesa-utils

  kmscube:
    plugin: nil
    stage-packages:
      - kmscube

  vainfo:
    plugin: nil
    stage-packages:
      - vainfo

  vdpauinfo:
    plugin: nil
    stage-packages:
      - vdpauinfo

  vulkan-tools:
    plugin: nil
    stage-packages:
      - vulkan-tools

  cleanup:
    after:
      - drm-info
      - eglinfo
      - glmark2
      - kmscube
      - vainfo
      - vdpauinfo
      - vulkan-tools
    plugin: nil
    build-snaps: [ mesa-core20 ]
    override-prime: |
      set -eux
      cd /snap/mesa-core20/current/egl/lib
      find . -type f,l -exec rm -f $SNAPCRAFT_PRIME/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/{} \;
      rm -fr "$SNAPCRAFT_PRIME/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri"
      rm -fr "$SNAPCRAFT_PRIME/usr/share/"{bug,doc,doc-base,drirc.d,glvnd,libdrm,lintian,man}
