name: graphics-test-tools
version: "22.04"
base: core22
summary: Tools helpful in debugging graphics stacks
description: |
  - drm-info (MIT):
    List the capabilities and current settings of this device's DRM
    (Direct Rendering Manager) hardware.
  - glmark2-es2 (GPLv3):
    OpenGL ES 2.0 X11 benchmark.
  - glmark2-es2-wayland (GPLv3):
    OpenGL ES 2.0 Wayland benchmark.
  - eglinfo (MIT):
    Dump information about the available EGL setup.
  - glxinfo (MIT):
    Dump information about the available GLX setup.
  - kmscube (MIT):
    Example KMS/GBM/EGL application
  - vainfo (MIT):
    Dump information about the available VAAPI (hardware video acceleration) setup.
  - vdpauinfo (MIT):
    Dump information about the available VDPAU (hardware video acceleration) setup.
  - vulkaninfo (Apache-2.0):
    Dump information about the available Vulkan setup.
  - vkcube (Apache-2.0):
    Test the Vulkan setup.

  This snap uses the graphics-core22 interface to gain support graphics hardware.
  It can be used to verify custom graphics-core22 provider implementations.

  See https://mir-server.io/docs/the-graphics-core22-snap-interface) for more
  information.
website: https://github.com/MirServer/graphics-test-tools
contact: https://github.com/MirServer/graphics-test-tools/issues
license: Apache-2.0 AND GPL-3.0 AND MIT

grade: stable
confinement: strict

layout:
  /usr/share/drirc.d:
    bind: $SNAP/graphics/drirc.d
  /usr/libexec/libinput:
    symlink: $SNAP/usr/libexec/libinput
  /usr/share/libinput:
    symlink: $SNAP/usr/share/libinput

plugs:
  graphics-core22:
    interface: content
    target: $SNAP/graphics
    default-provider: mesa-core22

apps:
  drm-info:
    plugs:
      - opengl
    command: usr/bin/drm_info

  eglinfo:
    plugs:
      - opengl
      - wayland
      - x11
    command-chain:
      - bin/graphics-core22-wrapper
      - bin/wayland-launch
    command: usr/bin/eglinfo

  glmark2-es2:
    plugs:
      - opengl
      - x11
    command-chain:
      - bin/graphics-core22-wrapper
    command: usr/bin/glmark2-es2 --data-path $SNAP/usr/share/glmark2

  glmark2-es2-wayland:
    plugs:
      - opengl
      - wayland
    command-chain:
      - bin/graphics-core22-wrapper
      - bin/wayland-launch
    command: usr/bin/glmark2-es2-wayland --data-path $SNAP/usr/share/glmark2

  glxinfo:
    plugs:
      - opengl
      - x11
    command-chain:
      - bin/graphics-core22-wrapper
    command: usr/bin/glxinfo

  kmscube:
    plugs:
      - opengl
    command-chain:
      - bin/graphics-core22-wrapper
    command: usr/bin/kmscube

  vainfo:
    plugs:
      - opengl
    command-chain:
      - bin/graphics-core22-wrapper
    command: usr/bin/vainfo

  vdpauinfo:
    plugs:
      - opengl
      - x11
    command-chain:
      - bin/graphics-core22-wrapper
    command: usr/bin/vdpauinfo

  vulkaninfo:
    plugs:
      - opengl
      - x11
    command-chain:
      - bin/graphics-core22-wrapper
    command: usr/bin/vulkaninfo

  vkcube:
    plugs:
      - opengl
      - x11
    command-chain:
      - bin/graphics-core22-wrapper
    command: usr/bin/vkcube

  libinput-debug-events:
    plugs:
      - hardware-observe
      - raw-input
    command: usr/bin/libinput debug-events

parts:
  scripts:
    plugin: dump
    source: scripts
    stage-packages:
      - inotify-tools

  drm-info:
    plugin: nil
    stage-packages:
      - drm-info

  eglinfo:
    plugin: nil
    source: .
    stage-packages:
      - mesa-utils-extra

  glmark2:
    plugin: nil
    source: .
    stage-packages:
      - glmark2-es2
      - glmark2-es2-wayland

  kmscube:
    plugin: nil
    stage-packages:
      - kmscube

  vainfo:
    plugin: nil
    stage-packages:
      - vainfo

  vdpauinfo:
    plugin: nil
    stage-packages:
      - vdpauinfo

  vulkan-tools:
    plugin: nil
    stage-packages:
      - vulkan-tools

  libinput-tools:
    plugin: nil
    stage-packages:
      - libinput-tools

  graphics-core22:
    after:
      - drm-info
      - eglinfo
      - glmark2
      - kmscube
      - vainfo
      - vdpauinfo
      - vulkan-tools
      - libinput-tools
    source: https://github.com/MirServer/graphics-core22.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/graphics-core22-cleanup mesa-core22
      rm -rf ${CRAFT_PRIME}/usr/share/{doc,man}
    prime:
      - bin/graphics-core22-wrapper
