name: graphics-test-tools
version: "22.04"
base: core22
summary: Tools helpful in debugging graphics stacks
description: |
  - drm-info:
    List the capabilities and current settings of this device's DRM
    (Direct Rendering Manager) hardware.
  - glmark2-es2:
    OpenGL ES 2.0 X11 benchmark.
  - glmark2-es2-wayland:
    OpenGL ES 2.0 Wayland benchmark.
  - eglinfo:
    Dump information about the available EGL setup.
  - glxinfo:
    Dump information about the available GLX setup.
  - vainfo:
    Dump information about the available VAAPI (hardware video acceleration) setup.
  - vdpauinfo:
    Dump information about the available VDPAU (hardware video acceleration) setup.
  - vulkaninfo:
    Dump information about the available Vulkan setup.
  - vkcube:
    Test the Vulkan setup.

grade: stable
confinement: strict

layout:
  /usr/share/drirc.d:
    bind: $SNAP/graphics/drirc.d

plugs:
  graphics-core22:
    interface: content
    target: $SNAP/graphics
    default-provider: mesa-core22/edge

apps:
  drm-info:
    plugs:
      - opengl
    command: usr/bin/drm_info

  eglinfo:
    plugs:
      - opengl
      - wayland
      - x11
    command-chain:
      - bin/graphics-core22-wrapper
      - bin/wayland-launch
    command: usr/bin/eglinfo

  glmark2-es2:
    plugs:
      - opengl
      - x11
    command-chain:
      - bin/graphics-core22-wrapper
    command: usr/bin/glmark2-es2 --data-path $SNAP/usr/share/glmark2

  glmark2-es2-wayland:
    plugs:
      - opengl
      - wayland
    command-chain:
      - bin/graphics-core22-wrapper
      - bin/wayland-launch
    command: usr/bin/glmark2-es2-wayland --data-path $SNAP/usr/share/glmark2

  glxinfo:
    plugs:
      - opengl
      - x11
    command-chain:
      - bin/graphics-core22-wrapper
    command: usr/bin/glxinfo

  vainfo:
    plugs:
      - opengl
    command-chain:
      - bin/graphics-core22-wrapper
    command: usr/bin/vainfo

  vdpauinfo:
    plugs:
      - opengl
      - x11
    command-chain:
      - bin/graphics-core22-wrapper
    command: usr/bin/vdpauinfo

  vulkaninfo:
    plugs:
      - opengl
      - x11
    command-chain:
      - bin/graphics-core22-wrapper
    command: usr/bin/vulkaninfo

  vkcube:
    plugs:
      - opengl
      - x11
    command-chain:
      - bin/graphics-core22-wrapper
    command: usr/bin/vkcube

parts:
  scripts:
    plugin: dump
    source: scripts
    stage-packages:
      - inotify-tools

  drm-info:
    plugin: nil
    stage-packages:
      - drm-info

  eglinfo:
    plugin: nil
    source: .
    stage-packages:
      - mesa-utils-extra

  glmark2:
    plugin: nil
    source: .
    stage-packages:
      - glmark2-es2
      - glmark2-es2-wayland

  vainfo:
    plugin: nil
    stage-packages:
      - vainfo

  vdpauinfo:
    plugin: nil
    stage-packages:
      - vdpauinfo

  vulkan-tools:
    plugin: nil
    stage-packages:
      - vulkan-tools

  graphics-core22:
    after:
      - drm-info
      - eglinfo
      - glmark2
      - vainfo
      - vdpauinfo
      - vulkan-tools
    source: https://github.com/MirServer/graphics-core22.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/graphics-core22-cleanup mesa-core22
      rm -rf ${CRAFT_PRIME}/usr/share/{doc,man}
    prime:
      - bin/graphics-core22-wrapper
